# Generated by Django 5.0.1 on 2025-07-22 16:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session ID per utenti anonimi', max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrello',
                'verbose_name_plural': 'Carrelli',
                'db_table': 'orders_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('special_instructions', models.TextField(blank=True, max_length=500)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prezzo unitario al momento aggiunta', max_digits=8)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('extra_ingredients', models.ManyToManyField(blank=True, help_text='Ingredienti extra', to='products.ingredient')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pizza')),
                ('removed_ingredients', models.ManyToManyField(blank=True, related_name='removed_from_carts', to='products.ingredient')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pizzasize')),
            ],
            options={
                'verbose_name': 'Elemento Carrello',
                'verbose_name_plural': 'Elementi Carrello',
                'db_table': 'orders_cart_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(help_text='Numero ordine pubblico', max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=17)),
                ('order_type', models.CharField(choices=[('delivery', 'Consegna a Domicilio'), ('pickup', 'Ritiro in Negozio'), ('dine_in', 'Consumo sul Posto')], default='delivery', max_length=20)),
                ('delivery_address_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('confirmed', 'Confermato'), ('preparing', 'In Preparazione'), ('ready', 'Pronto'), ('out_for_delivery', 'In Consegna'), ('delivered', 'Consegnato'), ('cancelled', 'Annullato'), ('refunded', 'Rimborsato')], default='pending', max_length=20)),
                ('special_instructions', models.TextField(blank=True, max_length=1000)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=17)),
                ('vehicle_info', models.CharField(blank=True, help_text='Tipo veicolo, targa', max_length=100)),
                ('status', models.CharField(choices=[('assigned', 'Assegnato'), ('picked_up', 'Ritirato'), ('in_transit', 'In Transito'), ('arrived', 'Arrivato'), ('delivered', 'Consegnato'), ('failed', 'Consegna Fallita')], default='assigned', max_length=20)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('customer_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='orders.order')),
            ],
            options={
                'verbose_name': 'Info Consegna',
                'verbose_name_plural': 'Info Consegne',
                'db_table': 'orders_delivery_info',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('extra_ingredients_snapshot', models.JSONField(default=list, help_text='Lista ingredienti extra al momento ordine')),
                ('removed_ingredients_snapshot', models.JSONField(default=list, help_text='Lista ingredienti rimossi')),
                ('special_instructions', models.TextField(blank=True, max_length=500)),
                ('preparation_status', models.CharField(choices=[('pending', 'In Attesa'), ('preparing', 'In Preparazione'), ('ready', 'Pronto')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pizza')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pizzasize')),
            ],
            options={
                'verbose_name': 'Elemento Ordine',
                'verbose_name_plural': 'Elementi Ordine',
                'db_table': 'orders_order_item',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('card', 'Carta di Credito'), ('paypal', 'PayPal'), ('cash', 'Contanti'), ('bank_transfer', 'Bonifico'), ('voucher', 'Buono')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('processing', 'In Elaborazione'), ('completed', 'Completato'), ('failed', 'Fallito'), ('cancelled', 'Annullato'), ('refunded', 'Rimborsato'), ('partially_refunded', 'Parzialmente Rimborsato')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='ID transazione gateway', max_length=100)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Response completa gateway')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refund_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamenti',
                'db_table': 'orders_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
